#!/usr/bin/env bash

# TODO: Add some options to this thing

BUILD_DIRECTORY='.build'

if [ ! -e $BUILD_DIRECTORY/bin/ob ]
then
  cmake --workflow --preset debug
fi

cd tests

for f in expect/*.ob
do
  echo "Generating expect file for $f"

  outf=$(mktemp "${TMPDIR:-/tmp/}out.$(basename -s .ob "$f").XXXXXXXXXXXX")
  errf=$(mktemp "${TMPDIR:-/tmp/}err.$(basename -s .ob "$f").XXXXXXXXXXXX")

  tgtf="entries/$(basename -s .ob "$f").expect"
  resf="entries/$(basename -s .ob "$f").expect2"

  ../$BUILD_DIRECTORY/bin/ob --verbose=0 "$f" \
     > "$outf" \
    2> "$errf" \

  touch "$resf"

  echo "-- PROGRAM $(basename "$f") --"  > "$resf"
  cat "$f"                              >> "$resf"
  echo "-- STDOUT --"                   >> "$resf"
  cat "$outf"                           >> "$resf"
  echo "-- STDERR --"                   >> "$resf"
  cat "$errf"                           >> "$resf"

  if test -e "$tgtf" && grep -F '(any)' "$tgtf"
  then
    echo "File cannot be modified. Merge manually with the outputs from $BUILD_DIRECTORY"
    rm "$resf"
  else
    mv "$resf" "$tgtf"
  fi
done
