#!/usr/bin/env bash

# TODO: Add some options to this thing

BUILD_DIRECTORY='.build'

if [ ! -e $BUILD_DIRECTORY/bin/ob ]
then
  cmake --workflow --preset debug
fi

for f in tests/entries/*.ob
do
  echo "Generating expects for $f"

  outf=$(mktemp "${TMPDIR:-/tmp/}out.$(basename -s .ob "$f").XXXXXXXXXXXX")
  errf=$(mktemp "${TMPDIR:-/tmp/}err.$(basename -s .ob "$f").XXXXXXXXXXXX")

  tgtf="tests/entries/$(basename -s .ob "$f").expect"
  resf="tests/entries/$(basename -s .ob "$f").expect2"

  $BUILD_DIRECTORY/bin/ob --verbose=0 "$f" \
     > "$outf" \
    2> "$errf" \

  touch "$resf"

  echo "-- PROGRAM $(basename "$f") --"  > "$resf"
  cat "$f"                              >> "$resf"
  echo "-- STDOUT --"                   >> "$resf"
  cat "$outf"                           >> "$resf"
  echo "-- STDERR --"                   >> "$resf"
  cat "$errf"                           >> "$resf"

  if grep '(any)' "$tgtf"
  then
    echo "File cannot be changed."
    rm "$resf"
  else
    mv "$resf" "$tgtf"
  fi
done

exit 0

for f in tests/entries/*.ob
do
  echo "Generating snapshots for $f"

  basename="$(basename -s .ob $f)"

  if [ ! -e tests/stdout/$basename ]
  then
    echo "Capturing stdout..."
    $BUILD_DIRECTORY/bin/ob --verbose=0 $f --capture-stdout tests/stdout/$basename
  fi

  if [ ! -e tests/stderr/$basename ]
  then
    echo "Capturing stderr..."
    $BUILD_DIRECTORY/bin/ob --verbose=0 $f --capture-stderr tests/stderr/$basename
  fi
done
