option(
  'build-docs',
  type: 'boolean',
  value: true,
  description: 'Build the documentation with Doxygen'
)

option(
  'build-tests',
  type: 'boolean',
  value: true,
  description: 'Build the tests'
)

option(
  'enable-asserts',
  type: 'boolean',
  value: true,
  description: 'Expand the `ASSERT` macro'
)

option(
  'enable-checks',
  type: 'boolean',
  value: true,
  description: 'Enable the `if(CHECKS)` sections'
)
